Downstream image and script changes
- Use VMware repository for base image
- Do not download OVS source code
- Do not install IPsec related packages by default
- Remove unnecessary OVS patches from apply-patches.sh
- Configure iptables-wrapper for Ubuntu image

2023-12-26:
- Remove whereabouts per upstream change

2024-07-22:
- Fix IPsec build error caused by incorrect image tag

Signed-off-by: Xu Liu <xliu2@vmware.com>

Note: this should be squashed to 0a80591 on the next rebase

Signed-off-by: Xu Liu <xu.liu@broadcom.com>

Install iproute2 in Ubuntu Image

antctl support bundle needs the ip command.

Add Dockerfile for Debian builds

Add support for building OVS image and Antrea images with
Debian as base image.

Signed-off-by: Xu Liu <xliu2@vmware.com>

Add Dockerfile for Photon builds

Add support for building OVS image and Antrea images with
Photon as base image.

Signed-off-by: Xu Liu <xliu2@vmware.com>

Add Dockerfile for Photon builds

Add support for building OVS image and Antrea images with
Photon as base image.

Signed-off-by: Xu Liu <xliu2@vmware.com>

Adjust UBI Dockerfile for OVS and Antrea

Signed-off-by: Xu Liu <xliu2@vmware.com>

Support building Photon locally

Signed-off-by: Xu Liu <xliu2@vmware.com>

Support IPSec in Photon base image

Signed-off-by: Xu Liu <xliu2@vmware.com>

Install python3-curses in OVS photon

Install gzip in Photon to fix the issue of logrotate

Logrotate uses gzip to compress the log files by default.
Added an e2e test case to prevent such issues in the future.

Add net-tools to install the hostname command to prevent
errors from ovs-ctl.

Fixes: https://bugzilla.eng.vmware.com/show_bug.cgi?id=3312394

Signed-off-by: Xu Liu <xliu2@vmware.com>

Install Suricata in Debian images

Signed-off-by: Xu Liu <xliu2@vmware.com>

Update Photon openvswitch.spec to 2.17.0

Update openvwitch.spec for Photon

Signed-off-by: Xu Liu <xliu2@vmware.com>

Define OVS version in photon SPEC file

Signed-off-by: Xu Liu <xliu2@vmware.com>

Build different images for antrea-agent and antrea-controller

Build debian image for flow-aggregator

Support building flow-aggregator ubi image

Signed-off-by: Xu Liu <xliu2@vmware.com>

Adapt to Upstream Dockerfile for flow-aggregaror

Install ca-certificates in flow-aggregator. This is for supporting
the S3 uploader.

Build and install Suricata in Photon images

Signed-off-by: Xu Liu <xliu2@vmware.com>

Support installing Suricata from local packages

Signed-off-by: Xu Liu <xliu2@vmware.com>

Use broadcom mirror repo for docker images

diff --git a/build/images/base/Dockerfile b/build/images/base/Dockerfile
--- a/build/images/base/Dockerfile
+++ b/build/images/base/Dockerfile
@@ -12,49 +12,93 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-FROM ubuntu:24.04 AS cni-binaries
+ARG BUILD_TAG
+FROM dockerhub.artifactory.vcfd.broadcom.net/ubuntu:24.04 as cni-binaries
 
 ARG CNI_BINARIES_VERSION
+ARG DOWNLOAD_CNI_BINARIES=false
+
+COPY cni-plugins-*.tgz /tmp
+
+RUN echo 'Acquire::https::Verify-Peer "false";' > /etc/apt/apt.conf.d/99insecure && \
+    echo 'Acquire::https::Verify-Host "false";' >> /etc/apt/apt.conf.d/99insecure && \
+    echo 'APT::Get::AllowUnauthenticated "true";' >> /etc/apt/apt.conf.d/99insecure
+
+RUN mv /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources.bak
+
+COPY <<EOF /etc/apt/sources.list.d/broadcom.sources
+Types: deb
+URIs: https://packages.vcfd.broadcom.net/ubuntu-remote/ubuntu/
+Suites: noble noble-updates noble-backports
+Components: main universe restricted multiverse
+Trusted: yes
+Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
+
+Types: deb
+URIs: https://packages.vcfd.broadcom.net/ubuntu-remote/ubuntu/
+Suites: noble-security
+Components: main universe restricted multiverse
+Trusted: yes
+Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
+EOF
 
 RUN apt-get update && \
-    apt-get install -y --no-install-recommends wget ca-certificates
+    apt-get install -y --no-install-recommends wget ca-certificates && \
+    rm -rf /var/cache/apt/* /var/lib/apt/lists/*
 
 # Leading dot is required for the tar command below
 ENV CNI_PLUGINS="./host-local ./loopback ./portmap ./bandwidth"
 
 # Download containernetworking plugin binaries for the correct architecture
 RUN set -eux; \
-    dpkgArch="$(dpkg --print-architecture)"; \
-    case "${dpkgArch##*-}" in \
-         amd64) pluginsArch='amd64' ;; \
-	 armhf) pluginsArch='arm' ;; \
-	 arm64) pluginsArch='arm64' ;; \
-         *) pluginsArch=''; echo >&2; echo >&2 "unsupported architecture '$dpkgArch'"; echo >&2 ; exit 1 ;; \
-    esac; \
     mkdir -p /opt/cni/bin; \
-    wget -q -O - https://github.com/containernetworking/plugins/releases/download/$CNI_BINARIES_VERSION/cni-plugins-linux-${pluginsArch}-$CNI_BINARIES_VERSION.tgz | tar xz -C /opt/cni/bin $CNI_PLUGINS
+    if ${DOWNLOAD_CNI_BINARIES}; then \
+        dpkgArch="$(dpkg --print-architecture)"; \
+        case "${dpkgArch##*-}" in \
+            amd64) pluginsArch='amd64' ;; \
+        armhf) pluginsArch='arm' ;; \
+        arm64) pluginsArch='arm64' ;; \
+            *) pluginsArch=''; echo >&2; echo >&2 "unsupported architecture '$dpkgArch'"; echo >&2 ; exit 1 ;; \
+        esac; \
+        wget --no-check-certificate -q -O - https://github.com/containernetworking/plugins/releases/download/$CNI_BINARIES_VERSION/cni-plugins-linux-${pluginsArch}-$CNI_BINARIES_VERSION.tgz | tar xz -C /opt/cni/bin $CNI_PLUGINS; \
+    else \
+        tar -zxvf /tmp/cni-plugins-*.tgz -C /opt/cni/bin $CNI_PLUGINS; \
+    fi
 
 FROM antrea-openvswitch
 
 ARG SURICATA_VERSION
+ARG INSTALL_SURICATA_FROM_PACKAGE=false
 
 LABEL maintainer="Antrea <projectantrea-dev@googlegroups.com>"
 LABEL description="An Ubuntu based Docker base image for Antrea."
 
+# Disable SSL peer verification, host verification and allow unauthenticated packages
+# to fix build failure. This is usually not recommended, but should be Ok for a trusted
+# site from Broadcom.
+RUN echo 'Acquire::https::Verify-Peer "false";' > /etc/apt/apt.conf.d/99insecure && \
+    echo 'Acquire::https::Verify-Host "false";' >> /etc/apt/apt.conf.d/99insecure && \
+    echo 'APT::Get::AllowUnauthenticated "true";' >> /etc/apt/apt.conf.d/99insecure && \
+    echo "deb https://packages.vcfd.broadcom.net/ubuntu-remote/ubuntu jammy main restricted universe" > /etc/apt/sources.list && \
+    echo "deb https://packages.vcfd.broadcom.net/ubuntu-remote/ubuntu jammy-security main restricted" >> /etc/apt/sources.list && \
+    echo "deb https://packages.vcfd.broadcom.net/ubuntu-remote/ubuntu jammy-updates main restricted" >> /etc/apt/sources.list
+
 USER root
 
-# See https://github.com/kubernetes-sigs/iptables-wrappers
-# /iptables-wrapper-installer.sh will have permissions of 600.
-# --chmod=700 doesn't work with older versions of Docker and requires DOCKER_BUILDKIT=1, so we use
-# chmod in the RUN command below instead.
-ADD https://raw.githubusercontent.com/kubernetes-sigs/iptables-wrappers/9e6ce59c864623ea71a6f7d59c35fcb13a919b87/iptables-wrapper-installer.sh /iptables-wrapper-installer.sh
+COPY iptables-wrapper-installer.sh /iptables-wrapper-installer.sh
+COPY suricata*.deb /tmp
 
-RUN apt-get update && apt-get install -y --no-install-recommends ipset jq inotify-tools gpg-agent software-properties-common && \
+RUN apt-get update && apt-get install -y --no-install-recommends ipset jq iproute2 inotify-tools gpg-agent software-properties-common && \
     # ethtool is for commercial release Antrea to toggle Geneve checksum offload.
     apt-get install -y --no-install-recommends ethtool && \
-    add-apt-repository ppa:oisf/suricata-${SURICATA_VERSION} && apt-get update && apt-get install -y suricata && \
+    if ${INSTALL_SURICATA_FROM_PACKAGE}; then \
+        apt install -y /tmp/suricata*.deb --no-install-recommends && \
+        apt-mark hold suricata; \
+    else \
+        SURICATA_VERSION=$(echo ${SURICATA_VERSION} | cut -d'.' -f1-2); \
+        add-apt-repository ppa:oisf/suricata-${SURICATA_VERSION} && apt-get update && apt-get install -y suricata; \
+    fi && \
     apt-get remove -y gpg-agent software-properties-common && apt-get autoremove -y && rm -rf /var/cache/apt/* /var/lib/apt/lists/* && \
-    chmod +x /iptables-wrapper-installer.sh && \
     /iptables-wrapper-installer.sh
 
 COPY --from=cni-binaries /opt/cni/bin /opt/cni/bin
